### ISSUE TITLE
Virtual Functions | C++

### ISSUE THREAD

**Issue by vipul-2003** [shoaibrayeen/Algorithms#32]
hi there , 
i am vipul kumar singh , wanted to add code for the problem of c++ , 
The link of the question is [Virtual Functions](https://www.hackerrank.com/challenges/virtual-functions/problem) and it is important concept of c++ course called Virtual Fucntions 

please assign this to me @shoaibrayeen

**Comment by shoaibrayeen** [comment]
you can add a pr for the same @vipul-2003
